#!/bin/sh
set -e

BIN=led
OUTDIR=target/thumbv7em-none-eabihf/debug
HEX=$OUTDIR/$BIN.hex
ELF=$OUTDIR/$BIN

cargo clean
cargo build
cargo objcopy -- -O ihex $HEX
#teensy_loader_cli -w -mmcu=mk66fx1m0 $HEX -v